INSERT INTO countries (code, name, capital, continent) VALUES
('AF', 'Afghanistan', 'Kabul', 'Asien'),
('AL', 'Albanien', 'Tirana', 'Europa'),
('DZ', 'Algeriet', 'Alger', 'Afrika'),
('AD', 'Andorra', 'Andorra la Vella', 'Europa'),
('AO', 'Angola', 'Luanda', 'Afrika'),
('AG', 'Antigua och Barbuda', 'Saint John''s', 'Nordamerika'),
('AR', 'Argentina', 'Buenos Aires', 'Sydamerika'),
('AM', 'Armenien', 'Jerevan', 'Asien'),
('AU', 'Australien', 'Canberra', 'Oceanien'),
('AZ', 'Azerbajdzjan', 'Baku', 'Asien'),
('BS', 'Bahamas', 'Nassau', 'Nordamerika'),
('BH', 'Bahrain', 'Manama', 'Asien'),
('BD', 'Bangladesh', 'Dhaka', 'Asien'),
('BB', 'Barbados', 'Bridgetown', 'Nordamerika'),
('BY', 'Belarus', 'Minsk', 'Europa'),
('BE', 'Belgien', 'Bryssel', 'Europa'),
('BZ', 'Belize', 'Belmopan', 'Nordamerika'),
('BJ', 'Benin', 'Porto-Novo', 'Afrika'),
('BT', 'Bhutan', 'Thimphu', 'Asien'),
('BO', 'Bolivia', 'Sucre', 'Sydamerika'),
('BA', 'Bosnien och Hercegovina', 'Sarajevo', 'Europa'),
('BW', 'Botswana', 'Gaborone', 'Afrika'),
('BR', 'Brasilien', 'Brasília', 'Sydamerika'),
('BN', 'Brunei', 'Bandar Seri Begawan', 'Asien'),
('BG', 'Bulgarien', 'Sofia', 'Europa'),
('BF', 'Burkina Faso', 'Ouagadougou', 'Afrika'),
('BI', 'Burundi', 'Gitega', 'Afrika'),
('CF', 'Centralafrikanska republiken', 'Bangui', 'Afrika'),
('CL', 'Chile', 'Santiago de Chile', 'Sydamerika'),
('CO', 'Colombia', 'Bogotá', 'Sydamerika'),
('CR', 'Costa Rica', 'San José', 'Nordamerika'),
('CY', 'Cypern', 'Nicosia', 'Europa'),
('DJ', 'Djibouti', 'Djibouti', 'Afrika'),
('DM', 'Dominica', 'Roseau', 'Nordamerika'),
('DO', 'Dominikanska republiken', 'Santo Domingo', 'Nordamerika'),
('EC', 'Ecuador', 'Quito', 'Sydamerika'),
('EG', 'Egypten', 'Kairo', 'Afrika'),
('GQ', 'Ekvatorialguinea', 'Malabo', 'Afrika'),
('SV', 'El Salvador', 'San Salvador', 'Nordamerika'),
('CI', 'Elfenbenskusten', 'Yamoussoukro', 'Afrika'),
('ER', 'Eritrea', 'Asmara', 'Afrika'),
('EE', 'Estland', 'Tallinn', 'Europa'),
('ET', 'Etiopien', 'Addis Abeba', 'Afrika'),
('FJ', 'Fiji', 'Suva', 'Asien'),
('PH', 'Filippinerna', 'Manila', 'Asien'),
('FO', 'Färöarna', 'Torshamn', 'Europa'),
('AE', 'Förenade arabemiraten', 'Abu Dhabi', 'Asien'),
('GA', 'Gabon', 'Libreville', 'Afrika'),
('GM', 'Gambia', 'Banjul', 'Afrika'),
('GE', 'Georgien', 'Tbilisi', 'Europa'),
('GH', 'Ghana', 'Accra', 'Afrika'),
('GR', 'Grekland', 'Aten', 'Europa'),
('GD', 'Grenada', 'Saint George''s', 'Nordamerika'),
('GL', 'Grönland', 'Nuuk', 'Europa'),
('GT', 'Guatemala', 'Guatemala City', 'Nordamerika'),
('GN', 'Guinea', 'Conakry', 'Afrika'),
('GW', 'Guinea-Bissau', 'Bissau', 'Afrika'),
('GY', 'Guyana', 'Georgetown', 'Sydamerika'),
('HT', 'Haiti', 'Port-au-Prince', 'Nordamerika'),
('HN', 'Honduras', 'Tegucigalpa', 'Nordamerika'),
('IN', 'Indien', 'New Delhi', 'Asien'),
('ID', 'Indonesien', 'Jakarta', 'Asien'),
('IQ', 'Irak', 'Bagdad', 'Asien'),
('IR', 'Iran', 'Teheran', 'Asien'),
('IE', 'Irland', 'Dublin', 'Europa'),
('IL', 'Israel', 'Jerusalem', 'Asien'),
('JM', 'Jamaica', 'Kingston', 'Nordamerika'),
('YE', 'Jemen', 'Sanaa', 'Asien'),
('JO', 'Jordanien', 'Amman', 'Asien'),
('KH', 'Kambodja', 'Phnom Penh', 'Asien'),
('CM', 'Kamerun', 'Yaoundé', 'Afrika'),
('CA', 'Kanada', 'Ottawa', 'Nordamerika'),
('CV', 'Kap Verde', 'Praia', 'Afrika'),
('KZ', 'Kazakstan', 'Astana', 'Asien'),
('KE', 'Kenya', 'Nairobi', 'Afrika'),
('CN', 'Kina', 'Peking', 'Asien'),
('KG', 'Kirgizistan', 'Bisjkek', 'Asien'),
('KI', 'Kiribati', 'Tarawa', 'Oceanien'),
('KM', 'Komorerna', 'Moroni', 'Afrika'),
('CG', 'Kongo-Brazzaville', 'Brazzaville', 'Afrika'),
('CD', 'Kongo-Kinshasa', 'Kinshasa', 'Afrika'),
('XK', 'Kosovo', 'Pristina', 'Europa'),
('HR', 'Kroatien', 'Zagreb', 'Europa'),
('CU', 'Kuba', 'Havanna', 'Nordamerika'),
('KW', 'Kuwait', 'Kuwait', 'Asien'),
('LA', 'Laos', 'Vientiane', 'Asien'),
('LS', 'Lesotho', 'Maseru', 'Afrika'),
('LV', 'Lettland', 'Riga', 'Europa'),
('LB', 'Libanon', 'Beirut', 'Asien'),
('LR', 'Liberia', 'Monrovia', 'Afrika'),
('LY', 'Libyen', 'Tripoli', 'Afrika'),
('LI', 'Liechtenstein', 'Vaduz', 'Europa'),
('LT', 'Litauen', 'Vilnius', 'Europa'),
('LU', 'Luxemburg', 'Luxemburg', 'Europa'),
('MG', 'Madagaskar', 'Antananarivo', 'Afrika'),
('MW', 'Malawi', 'Lilongwe', 'Afrika'),
('MY', 'Malaysia', 'Kuala Lumpur', 'Asien'),
('MV', 'Maldiverna', 'Malé', 'Asien'),
('ML', 'Mali', 'Bamako', 'Afrika'),
('MT', 'Malta', 'Valletta', 'Europa'),
('MA', 'Marocko', 'Rabat', 'Afrika'),
('MH', 'Marshallöarna', 'Majuro', 'Oceanien'),
('MR', 'Mauretanien', 'Nouakchott', 'Afrika'),
('MU', 'Mauritius', 'Port Louis', 'Afrika'),
('MX', 'Mexiko', 'Mexico City', 'Nordamerika'),
('FM', 'Mikronesiska federationen', 'Palikir', 'Oceanien'),
('MZ', 'Moçambique', 'Maputo', 'Afrika'),
('MD', 'Moldavien', 'Chișinău', 'Europa'),
('MC', 'Monaco', 'Monaco', 'Europa'),
('MN', 'Mongoliet', 'Ulan Bator', 'Asien'),
('ME', 'Montenegro', 'Podgorica', 'Europa'),
('MM', 'Myanmar', 'Naypyidaw', 'Asien'),
('NA', 'Namibia', 'Windhoek', 'Afrika'),
('NR', 'Nauru', 'Yaren', 'Oceanien'),
('NL', 'Nederländerna', 'Amsterdam', 'Europa'),
('NP', 'Nepal', 'Katmandu', 'Asien'),
('NI', 'Nicaragua', 'Managua', 'Nordamerika'),
('NE', 'Niger', 'Niamey', 'Afrika'),
('NG', 'Nigeria', 'Abuja', 'Afrika'),
('KP', 'Nordkorea', 'Pyongyang', 'Asien'),
('MK', 'Nordmakedonien', 'Skopje', 'Europa'),
('NZ', 'Nya Zeeland', 'Wellington', 'Oceanien'),
('OM', 'Oman', 'Muskat', 'Asien'),
('PK', 'Pakistan', 'Islamabad', 'Asien'),
('PW', 'Palau', 'Ngerulmud', 'Oceanien'),
('PA', 'Panama', 'Panama City', 'Nordamerika'),
('PG', 'Papua Nya Guinea', 'Port Moresby', 'Oceanien'),
('PY', 'Paraguay', 'Asunción', 'Sydamerika'),
('PE', 'Peru', 'Lima', 'Sydamerika'),
('PL', 'Polen', 'Warszawa', 'Europa'),
('PT', 'Portugal', 'Lissabon', 'Europa'),
('QA', 'Qatar', 'Doha', 'Asien'),
('RO', 'Rumänien', 'Bukarest', 'Europa'),
('RW', 'Rwanda', 'Kigali', 'Afrika'),
('RU', 'Ryssland', 'Moskva', 'Europa'),
('KN', 'Saint Kitts och Nevis', 'Basseterre', 'Nordamerika'),
('LC', 'Saint Lucia', 'Castries', 'Nordamerika'),
('VC', 'Saint Vincent och Grenadinerna', 'Kingstown', 'Nordamerika'),
('SB', 'Salomonöarna', 'Honiara', 'Oceanien'),
('WS', 'Samoa', 'Apia', 'Oceanien'),
('SM', 'San Marino', 'San Marino', 'Europa'),
('ST', 'São Tomé och Príncipe', 'São Tomé', 'Afrika'),
('SA', 'Saudiarabien', 'Riyadh', 'Asien'),
('CH', 'Schweiz', 'Bern', 'Europa'),
('SN', 'Senegal', 'Dakar', 'Afrika'),
('RS', 'Serbien', 'Belgrad', 'Europa'),
('SC', 'Seychellerna', 'Victoria', 'Afrika'),
('SL', 'Sierra Leone', 'Freetown', 'Afrika'),
('SG', 'Singapore', 'Singapore', 'Asien'),
('SK', 'Slovakien', 'Bratislava', 'Europa'),
('SI', 'Slovenien', 'Ljubljana', 'Europa'),
('SO', 'Somalia', 'Mogadishu', 'Afrika'),
('LK', 'Sri Lanka', 'Colombo', 'Asien'),
('SD', 'Sudan', 'Khartoum', 'Afrika'),
('SR', 'Surinam', 'Paramaribo', 'Sydamerika'),
('SZ', 'Swaziland', 'Mbabane', 'Afrika'),
('ZA', 'Sydafrika', 'Pretoria', 'Afrika'),
('KR', 'Sydkorea', 'Seoul', 'Asien'),
('SS', 'Sydsudan', 'Juba', 'Afrika'),
('SY', 'Syrien', 'Damaskus', 'Asien'),
('TJ', 'Tadzjikistan', 'Dusjanbe', 'Asien'),
('TW', 'Taiwan', 'Taipei', 'Asien'),
('TZ', 'Tanzania', 'Dodoma', 'Afrika'),
('TD', 'Tchad', 'NDjamena', 'Afrika'),
('TH', 'Thailand', 'Bangkok', 'Asien'),
('CZ', 'Tjeckien', 'Prag', 'Europa'),
('TG', 'Togo', 'Lomé', 'Afrika'),
('TO', 'Tonga', 'Nuku''alofa', 'Oceanien'),
('TT', 'Trinidad och Tobago', 'Port of Spain', 'Nordamerika'),
('TN', 'Tunisien', 'Tunis', 'Afrika'),
('TR', 'Turkiet', 'Ankara', 'Asien'),
('TM', 'Turkmenistan', 'Asjchabad', 'Asien'),
('TV', 'Tuvalu', 'Funafuti', 'Oceanien'),
('UG', 'Uganda', 'Kampala', 'Afrika'),
('UA', 'Ukraina', 'Kiev', 'Europa'),
('HU', 'Ungern', 'Budapest', 'Europa'),
('UY', 'Uruguay', 'Montevideo', 'Sydamerika'),
('UZ', 'Uzbekistan', 'Tasjkent', 'Asien'),
('VU', 'Vanuatu', 'Port Vila', 'Oceanien'),
('VA', 'Vatikanstaten', 'Vatikanstaden', 'Europa'),
('VE', 'Venezuela', 'Caracas', 'Sydamerika'),
('VN', 'Vietnam', 'Hanoi', 'Asien'),
('ZM', 'Zambia', 'Lusaka', 'Afrika'),
('ZW', 'Zimbabwe', 'Harare', 'Afrika'),
('AT', 'Österrike', 'Wien', 'Europa'),
('TL', 'Östtimor', 'Dili', 'Asien');